name: Send coverage report

on:
  push:
    branches:
      - main
    paths-ignore:
      - pyproject.toml

jobs:
  unit-tests-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      - name: Install the project
        run: uv sync --dev
      - name: Send coverage report
        run: |
          uv run pytest --cov newversion --cov-report=xml
      - name: Send coverage report
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
