name: Code style & unit tests

on:
  push:
    paths-ignore:
      - pyproject.toml
      - setup.cfg
      - CHANGELOG.md

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
        include:
          - version: "3.11"
            check-formatting: "true"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python for Poetry
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}
      - name: Install poetry
        run: |
          python -m pip install -U poetry pip
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}
          cache: "poetry"
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: |
          python -m pip install -U poetry pip wheel
          python -m poetry install -n
      - name: Install missing dependencies
        run: |
          poetry run pip install flake8 pytest
      - name: Install Node.js dependencies
        run: |
          npm install -g pyright
      - name: Code style
        if: ${{ matrix.check-formatting }}
        run: |
          poetry run black --check .
          poetry run isort -c .
      - name: Lint
        run: |
          poetry run flake8
      - name: Typing
        run: |
          poetry run npx pyright
      - name: Test
        run: |
          poetry run pytest
