name: Send coverage report

on:
  push:
    branches:
      - main
    paths-ignore:
      - pyproject.toml
      - setup.cfg
      - CHANGELOG.md

jobs:
  unit-tests-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install -U poetry pip wheel
          python -m poetry install -n
      - name: Send coverage report
        run: |
          python -m pytest --cov newversion --cov-report=xml
      - name: Send coverage report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
